#fibonnaci Each new term in the Fibonacci sequence is generated by 
#adding the previous two terms. By starting with 1 and 2, the first 
#10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not 
#exceed four million, find the sum of the even-valued terms.

#n = (n-1) + (n-2)

i = 1
n = 1
x = 0
even = []

while i < 4000000 and i > -10:
		
	x = i + n

#	print "I am i: ", i
#	print "I am n: ", n
#	print "I am x:",  x
#	print "\n"
	n = i
	i = x
	
	if i%2 == 0:
		even.append(i)


print sum(even)	
